name: Deploy to GitHub Pages

on:
  release:
    types: [published]  #Запускается только при новом релизе
jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps: # Получаеи текущее содержимое ветки gh-pages со всеми предыдущими версиями
      - name: Checkout code and gh-pages
        uses: actions/checkout@v3
        with:
          # Работаю с веткой gh-pages
          ref: gh-pages    
          # Сохраняю в папку gh-pages
          path: gh-pages     

      - name: Checkout main code # Получение кода из ветки main
        uses: actions/checkout@v3
        with:
          # Сохранение в папку main-code
          path: main-code    
      - name: Copy version to gh-pages # Копирование файлов, сохраняя все предыдущие версии
        run: |
          cd gh-pages
          # Создаю папку для новой версии
          mkdir -p ${{ github.event.release.tag_name }}
          
          # Копирую файлы в папку версии
          cp -r ../main-code/*.html ../main-code/ru ../main-code/en ./${{ github.event.release.tag_name }}/
          
          # Копирую файлы в корень для основной версии сайта
          cp -r ../main-code/*.html ../main-code/ru ../main-code/en ./
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_dir: ./gh-pages
          keep_files: true            